steps:
  # build the container image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sitenode-cloud-run:${SHORT_SHA}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sitenode-cloud-run']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'sitenode-cloud-run', '--image', 'gcr.io/$PROJECT_ID/sitenode-cloud-run:${SHORT_SHA}', '--region', 'us-central1-c', '--allow-unauthenticated']
  env:
  - 'PORT=8080'
images:
- gcr.io/$PROJECT_ID/sitenode-cloud-run
